# Generated by Django 4.2.17 on 2024-12-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('exchange', models.CharField(max_length=10)),
                ('assetType', models.CharField(max_length=10)),
                ('ipoDate', models.DateField()),
                ('delistingDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('watching', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
